[package]
name = "ashmaize-web"
edition.workspace = true
license.workspace = true
repository.workspace = true
version.workspace = true
description.workspace = true

publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
ashmaize = { path = "../.." }
wasm-bindgen = { version = "~0.2.100" }

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so isn't great for
# code size when deploying.
console_error_panic_hook = { version = "0.1.1", optional = true }

# `wee_alloc` is a tiny allocator for wasm that is only ~1K in code size
# compared to the default allocator's ~10K. It is slower than the default
# allocator, however.
wee_alloc = { version = "0.4.2", optional = true }


[dev-dependencies]
wasm-bindgen-test = "~0.3.50"
